print("Welcome to the Arithmetic Calculator!")
    print("Operations:")
    print("+  : Addition")
    print("-  : Subtraction")
    print("*  : Multiplication")
    print("/  : Division")
    print("%  : Modulo")
    print("<< : Left Shift")
    print(">> : Right Shift")