r=float(input("Enter radius:"))
l=float(input("Enter length:"))
b=float(input("Enter base:"))
h=float(input("Enter height:"))
print("Area of triangle:", 0.5*b*h)
print("Area of rectangle:", l*b)
print("Area of circle:", 3.14*r*r)
print("Area of sphere:", 3.14*4*r*r)